version: '3'
services:
  graphql:
    image: greefine/fs1-satory-back
    networks:
      - webgateway
      - default
    deploy:
      labels:
        traefik.port: '4000'
        traefik.frontend.rule: 'Host: api.greefine.app'
        traefik.docker.network: 'webgateway'

networks:
  webgateway:
    external: true
