version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '127.0.0.1:4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  graphql:
    build: .
    restart: always
    environment:
      - PRISMA_HOST=prisma
      - PRISMA_MANAGEMENT_API_JWT_SECRET=fs1-admin-pass!
      - JWT_SECRET=secret
    ports:
      - '4000:4000'
    depends_on:
      - prisma
    volumes:
      - ./:/fs1-satory-back

volumes:
  postgres:
